# Generated by Django 4.2.5 on 2023-10-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='MALE', max_length=6)),
                ('role', models.CharField(choices=[('USER', 'user'), ('HEALTH_PRACTITIONER', 'dietitian/health practitioner')], default='HEALTH_PRACTITIONER', max_length=30)),
                ('no_followers', models.PositiveBigIntegerField(blank=True, default=0)),
                ('no_followings', models.PositiveBigIntegerField(blank=True, default=0)),
                ('dietary_preference', models.CharField(blank=True, choices=[('VEGETARIAN', 'vegetarian'), ('VEGAN', 'vegan'), ('PESCATARIAN', 'pescatarian'), ('GLUTEN_FREE', 'gluten free'), ('DAIRY_FREE', 'dairy free'), ('LOW_CARB', 'low carb')], max_length=50, null=True)),
                ('health_goal', models.CharField(choices=[('WEIGHT_LOSS', 'weight loss'), ('MUSCLE_GAIN', 'muscle gain'), ('HEART_HEALTH', 'heart health'), ('LOW_CHOLESTEROL', 'low cholesterol'), ('BETTER_SLEEP', 'better sleep'), ('HEALTHY_AGING', 'healthy aging'), ('OVERALL_WELLNESS', 'overall wellness')], default='OVERALL_WELLNESS', max_length=50)),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'sedentary'), ('LIGHTLY_ACTIVE', 'lightly active'), ('MODERATELY_ACTIVE', 'moderately active'), ('VERY_ACTIVE', 'very active'), ('SUPER_ACTIVE', 'super active')], max_length=50)),
                ('specialization', models.CharField(blank=True, choices=[('GENERAL', 'General Nutrition'), ('SPORTS', 'Sports Nutrition'), ('PEDIATRIC', 'Pediatric'), ('WEIGHT_LOSS', 'Weight Loss'), ('DIABETICS', 'Diabetics'), ('HEART_HEALTH', 'Heart Health'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('ONCOLOGY', 'Oncology'), ('RENAL', 'Renal Nutrition'), ('VEGAN', 'Vegan and Vegetarian Nutrition'), ('FOOD_ALLERGIES', 'Food Allergies and Intolerance'), ('GERIATRICS', 'Geriatric Nutrition'), ('PREGNANCY', 'Pregnancy and Prenatal Nutrition'), ('POSTPARTUM', 'Postpartum Nutrition'), ('EATING_DISORDERS', 'Eating Disorders'), ('MEAL_PLANNING', 'Meal Planning'), ('CULINARY', 'Culinary Nutrition'), ('NUTRITIONAL_SUPPLEMENTS', 'Nutritional Supplements'), ('PUBLIC_HEALTH', 'Public Health Nutrition'), ('WEIGHT_GAIN', 'Healthy Weight Gain')], max_length=50, null=True)),
                ('professional_statement', models.TextField(blank=True, max_length=200, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
