# Generated by Django 4.2.5 on 2023-10-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(default=12, max_length=3),
        ),
    ]
