# Generated by Django 4.2.5 on 2023-10-25 17:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_taste_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='taste_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SWEET', 'sweet'), ('SAVOURY', 'savoury'), ('SPICY', 'spicy'), ('BITTER', 'bitter'), ('SOUR', 'sour'), ('HERBACEOUS', 'herbaceous'), ('UMAMI', 'umami'), ('GARLICKY', 'garlicky'), ('CITRUSY', 'citrusy'), ('MILD', 'mild'), ('AROMATIC', 'aromatic')], max_length=50),
        ),
    ]
