# Generated by Django 4.2.5 on 2023-10-24 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allergens',
            field=models.ManyToManyField(blank=True, choices=[('MILK', 'milk'), ('EGG', 'egg'), ('PEANUT', 'peanut'), ('SOY', 'soy'), ('WHEAT', 'wheat'), ('TREE_NUTS', 'tree nuts'), ('SHELLFISH', 'shellfish'), ('SESAME', 'sesame'), ('GARLIC', 'garlic')], to=settings.AUTH_USER_MODEL),
        ),
    ]
