# Generated by Django 4.2.5 on 2023-10-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_no_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='no_followers',
        ),
    ]
