# Generated by Django 4.2.5 on 2023-10-24 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cuisines',
            field=models.ManyToManyField(choices=[('ITALIAN', 'Italian'), ('MEDITERRAENIAN', 'Mediterraenian'), ('ASIAN', 'Asian'), ('MEXICAN', 'Mexican'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('AMERICAN', 'American'), ('FRENCH', 'French'), ('INDIAN', 'Indian'), ('AFRICAN', 'African')], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_conditions',
            field=models.ManyToManyField(blank=True, choices=[('DIABETICS', 'diabetics'), ('HYPERTENSION', 'hypertension'), ('KIDNEY_DISEASE', 'kidney disease'), ('LACTOSE_INTOLERANCE', 'lactose intolerance'), ('FRUCTOSE_INTOLERANCE', 'fructose intolerance'), ('OSTEOPOROSIS', 'osteoporosis'), ('PREGNANCY', 'pregnancy')], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taste_preferences',
            field=models.ManyToManyField(blank=True, choices=[('SWEET', 'sweet'), ('SAVOURY', 'savoury'), ('SPICY', 'spicy'), ('BITTER', 'bitter'), ('SOUR', 'sour'), ('HERBACEOUS', 'herbaceous'), ('UMAMI', 'umami'), ('GARLICKY', 'garlicky'), ('CITRUSY', 'citrusy'), ('MILD', 'mild'), ('AROMATIC', 'aromatic')], to=settings.AUTH_USER_MODEL),
        ),
    ]
