# Generated by Django 4.2.5 on 2023-10-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_taste_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='medical_conditions',
        ),
    ]
