# Generated by Django 4.2.5 on 2023-10-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_cuisines_customuser_medical_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('HEALTH_PRACTITIONER', 'dietitian/health practitioner')], default='USER', max_length=30),
        ),
    ]
