# Generated by Django 4.2.5 on 2023-10-25 17:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_medical_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='medical_conditions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DIABETICS', 'diabetics'), ('HYPERTENSION', 'hypertension'), ('KIDNEY_DISEASE', 'kidney disease'), ('LACTOSE_INTOLERANCE', 'lactose intolerance'), ('FRUCTOSE_INTOLERANCE', 'fructose intolerance'), ('OSTEOPOROSIS', 'osteoporosis'), ('PREGNANCY', 'pregnancy')], max_length=50),
        ),
    ]
