# Generated by Django 4.2.5 on 2023-10-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_no_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='no_followers',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
