# Generated by Django 4.2.5 on 2023-10-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_medical_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cuisines',
        ),
    ]
