# Generated by Django 4.2.5 on 2023-10-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_no_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='availability',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
