# Generated by Django 4.2.5 on 2023-10-25 17:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cuisines',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ITALIAN', 'Italian'), ('MEDITERRAENIAN', 'Mediterraenian'), ('ASIAN', 'Asian'), ('MEXICAN', 'Mexican'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('AMERICAN', 'American'), ('FRENCH', 'French'), ('INDIAN', 'Indian'), ('AFRICAN', 'African')], default='ITALIAN', max_length=50),
        ),
    ]
