# Generated by Django 4.2.5 on 2023-10-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_cuisines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allergens',
        ),
    ]
