# Generated by Django 4.2.5 on 2023-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_professional_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_on_boarded',
            field=models.BooleanField(default=False),
        ),
    ]
