# Generated by Django 4.2.5 on 2023-11-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='no_followers',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='no_followings',
        ),
    ]
