# Generated by Django 4.2.5 on 2023-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_no_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(default='https://www.gravatar.com/avatar', max_length=500),
        ),
    ]
