# Generated by Django 4.2.5 on 2024-03-18 17:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('VEGETARIAN', 'vegetarian'), ('VEGAN', 'vegan'), ('PESCATARIAN', 'pescatarian'), ('GLUTEN_FREE', 'gluten free'), ('DAIRY_FREE', 'dairy free'), ('LOW_CARB', 'low carb'), ('PREBIOTIC', 'prebiotic'), ('PROBIOTIC', 'probiotic'), ('HYDRATING', 'Hydrating')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='health_goal',
            field=models.CharField(choices=[('WEIGHT_LOSS', 'weight loss'), ('MUSCLE_GAIN', 'muscle gain'), ('HEART_HEALTH', 'heart health'), ('LOW_CHOLESTEROL', 'low cholesterol'), ('BETTER_SLEEP', 'better sleep'), ('HEALTHY_AGING', 'healthy aging'), ('OVERALL_WELLNESS', 'overall wellness'), ('ANTI_INFLAMMATORY', 'anti-inflammatory'), ('JOINT_HEALTH', 'joint health'), ('IMMUNE_SUPPORT', 'immune support'), ('GUT_HEALTH', 'gut health'), ('LOW_FAT', 'low fat'), ('WEIGHT_MAINTENANCE', 'weight maintenance'), ('CARDIOVASCULAR_HEALTH', 'cardiovascular health'), ('DIGESTIVE_HEALTH', 'digestive health'), ('BRAIN_HEALTH', 'brain health'), ('GUT_HEALTH', 'gut health'), ('RECOVERY', 'recovery')], default='OVERALL_WELLNESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taste_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SWEET', 'sweet'), ('SAVOURY', 'savoury'), ('SPICY', 'spicy'), ('BITTER', 'bitter'), ('SOUR', 'sour'), ('HERBACEOUS', 'herbaceous'), ('UMAMI', 'umami'), ('GARLICKY', 'garlicky'), ('CITRUSY', 'citrusy'), ('MILD', 'mild'), ('AROMATIC', 'aromatic'), ('CREAMY', 'creamy')], max_length=50),
        ),
    ]
