# Generated by Django 4.2.5 on 2024-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_dietary_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_goal',
            field=models.CharField(choices=[('WEIGHT_LOSS', 'weight loss'), ('MUSCLE_GAIN', 'muscle gain'), ('HEART_HEALTH', 'heart health'), ('LOW_CHOLESTEROL', 'low cholesterol'), ('BETTER_SLEEP', 'better sleep'), ('HEALTHY_AGING', 'healthy aging'), ('OVERALL_WELLNESS', 'overall wellness'), ('ANTI_INFLAMMATORY', 'anti-inflammatory'), ('JOINT_HEALTH', 'joint health'), ('IMMUNE_SUPPORT', 'immune support'), ('GUT_HEALTH', 'gut health'), ('LOW_FAT', 'low fat'), ('WEIGHT_MAINTENANCE', 'weight maintenance'), ('CARDIOVASCULAR_HEALTH', 'cardiovascular health'), ('DIGESTIVE_HEALTH', 'digestive health'), ('BRAIN_HEALTH', 'brain health'), ('RECOVERY', 'recovery')], default='OVERALL_WELLNESS', max_length=50),
        ),
    ]
