# Generated by Django 4.2.5 on 2024-05-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_is_verified_customuser_vote_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('GENERAL', 'general'), ('VEGETARIAN', 'vegetarian'), ('VEGAN', 'vegan'), ('PESCATARIAN', 'pescatarian'), ('GLUTEN_FREE', 'gluten free'), ('DAIRY_FREE', 'dairy free'), ('LOW_CARB', 'low carb'), ('PREBIOTIC', 'prebiotic'), ('PROBIOTIC', 'probiotic'), ('HYDRATING', 'Hydrating')], max_length=50),
        ),
    ]
