# Generated by Django 4.2.5 on 2024-06-06 18:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_goal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('WEIGHT_LOSS', 'weight loss'), ('MUSCLE_GAIN', 'muscle gain'), ('HEART_HEALTH', 'heart health'), ('LOW_CHOLESTEROL', 'low cholesterol'), ('BETTER_SLEEP', 'better sleep'), ('HEALTHY_AGING', 'healthy aging'), ('OVERALL_WELLNESS', 'overall wellness'), ('ANTI_INFLAMMATORY', 'anti-inflammatory'), ('JOINT_HEALTH', 'joint health'), ('IMMUNE_SUPPORT', 'immune support'), ('GUT_HEALTH', 'gut health'), ('LOW_FAT', 'low fat'), ('WEIGHT_MAINTENANCE', 'weight maintenance'), ('CARDIOVASCULAR_HEALTH', 'cardiovascular health'), ('DIGESTIVE_HEALTH', 'digestive health'), ('BRAIN_HEALTH', 'brain health'), ('RECOVERY', 'recovery')], default='OVERALL_WELLNESS', max_length=50),
        ),
    ]
