# Generated by Django 4.2.7 on 2024-06-15 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_health_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('PREFER_NOT_TO_SAY', 'prefer_not_to_say')], default='PREFER_NOT_TO_SAY', max_length=30),
        ),
    ]
