version: '3'

services:
  web:
    build:
      context: .
    container_name: user-service
    env_file:
      - .env
    # volumes:
    #   - .:/code
    develop:
      watch:
        - action: sync
          path: .
          target: /code/
    ports:
      - 8000:8000